### ISSUE TITLE
Doesn’t render KaTeX entities

### ISSUE THREAD

**Issue by flying-sheep** [fred-wang/webextension-native-mathml#12]
Looks like the `&ThinSpace;` entity doesn’t get interpreted on the KaTeX homepage:

![grafik](https://user-images.githubusercontent.com/291575/48190056-90655080-e339-11e8-8f81-3de4f0640cab.png)

**Comment by fred-wang** [comment]
@flying-sheep  I don't think the addon does anything for KaTeX but displaying their MathML output. I believe you should report this issue to KaTeX instead.

**Comment by flying-sheep** [comment]
OK, good point!
