### ISSUE TITLE
compatibility with gitter

### ISSUE THREAD

**Issue by holtzermann17** [fred-wang/webextension-native-mathml#5]
I've just created a bunch of PlanetMath discussion forums on Gitter, e.g., here:
https://gitter.im/planetmath/00_General

Their MathJaX-supported math doesn't render properly when I have the Native MathML plugin turned on.

( So, I initially opened a Gitter bug report here: https://gitlab.com/gitlab-org/gitter/gitter-markdown-processor/issues/9 )

But I now suspect that it is a Native MathML bug instead, since the expression shows up, e.g., in Chromium, or in Firefox with the Native MathML add-on disabled.

Native rendering works beautifully on the PlanetMath content generated by LaTeXML however!
http://planetmath.org/ErrorsCanCancelEachOtherOut  ...

**Comment by holtzermann17** [comment]
![image](https://user-images.githubusercontent.com/179958/36974267-f7dd1584-206d-11e8-8145-ca6768e04b16.png)

**Comment by auscompgeek** [comment]
Looks like this was fixed by #3. What are the odds.

**Comment by fred-wang** [comment]
@ holtzermann17  can you please try again with the latest version?

**Comment by fred-wang** [comment]
@holtzermann17

**Comment by holtzermann17** [comment]
Yes it works, thanks guys!
